import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next";
import {StrictMode} from "react";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StrictMode>
    <TRPCReactProvider>
      <html lang="en" className="h-full">
        <body
          className={`${inter.className} antialiased h-full`}
        >
          <Toaster />
          {children}
          <SpeedInsights />
        </body>
      </html>
    </TRPCReactProvider>
    </StrictMode>
  );
}
